[tool.black]
line-length = 100
target-version = ['py311']

[tool.ruff]
line-length = 100
fix = true
extend-select = ["E", "F", "I", "W", "UP"]
ignore = ["E501"]  # 忽略超行长警告
ignore = ["UP006"]

[tool.ruff.isort]
known-first-party = ["nf1_v3_core"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]
python_files = ["test_*.py"]
